/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Avatar: typeof import('./src/components/layout/header/right/ProfileAvatar.vue')['default']
    BreadCrumb: typeof import('./src/components/layout/header/left/BreadCrumb.vue')['default']
    CarChart: typeof import('./src/components/content/dashboard/CarChart.vue')['default']
    CollapseIcon: typeof import('./src/components/layout/header/left/CollapseIcon.vue')['default']
    EChart: typeof import('./src/components/common/chart/EChart.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    Error403: typeof import('./src/components/common/error/Error403.vue')['default']
    Error404: typeof import('./src/components/common/error/Error404.vue')['default']
    Error500: typeof import('./src/components/common/error/Error500.vue')['default']
    Fullscreen: typeof import('./src/components/layout/header/right/FullscreenToggle.vue')['default']
    FullscreenToggle: typeof import('./src/components/layout/header/right/FullscreenToggle.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    MainContent: typeof import('./src/components/layout/main/MainContent.vue')['default']
    MoreButton: typeof import('./src/components/layout/tab/right/MoreButton.vue')['default']
    ProfileAvatar: typeof import('./src/components/layout/header/right/ProfileAvatar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SideBar: typeof import('./src/components/layout/aside/SideBar.vue')['default']
    SubMenu: typeof import('./src/components/layout/menu/SubMenu.vue')['default']
    TabComponent: typeof import('./src/components/layout/tab/TabComponent.vue')['default']
    ThemeDrawer: typeof import('./src/components/layout/drawer/ThemeDrawer.vue')['default']
    ThemeModeSwitch: typeof import('./src/components/common/switch/ThemeModeSwitch.vue')['default']
    ThemeSetting: typeof import('./src/components/layout/header/right/ThemeSetting.vue')['default']
    ToolBarLeft: typeof import('./src/components/layout/header/ToolBarLeft.vue')['default']
    ToolBarRight: typeof import('./src/components/layout/header/ToolBarRight.vue')['default']
    VistorChart: typeof import('./src/components/content/dashboard/VistorChart.vue')['default']
  }
}
