server:
  port: 8888

spring:
  cloud:
    bus:
      refresh:
        enabled: true
  rabbitmq:
    host: 192.168.200.131
    port: 5672
    username: gewuyou
    password: youyong21126
    listener:
      simple:
        retry:
          enabled: true
          max-attempts: 3
          initial-interval: 3000
    virtual-host: /base-forge
  datasource:
    url: jdbc:mysql://192.168.200.131:3306/base_forge?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      # 数据库设置为0号数据库
      database: 0
      host: 192.168.200.131
      port: 6379
management:
  endpoints:
    web:
      exposure:
        include: '*'
      path-mapping:
        busrefresh: bus-refresh