server:
  port: 8888
spring:
  rabbitmq:
    host: 192.168.200.131
    port: 5672
    username: gewuyou
    password: youyong21126
    listener:
      simple:
        retry:
          enabled: true
          max-attempts: 3
          initial-interval: 3000
    virtual-host: /base-forge
  cloud:
    bus:
      refresh:
        enabled: true
management:
  endpoints:
    web:
      exposure:
        include: '*'
      path-mapping:
        busrefresh: bus-refresh
  endpoint:
    busrefresh:
      enabled: true