server:
  port: 8082
spring:
  cloud:
    gateway:
      enabled: true
      # 开启自动路由
      discovery:
        locator:
          enabled: true
      routes:
        - id: base-forge-admin
          uri: lb://base-forge-admin
          predicates:
            - Path=/api/v1/admin/**
          filters:
            - StripPrefix=2


      # 全局的跨域处理
      global-cors:
        # 解决options请求被拦截问题
        add-to-simple-url-handler-mapping: true
        corsConfigurations:
          '[/**]':
            allowedOrigins: # 允许哪些网站的跨域请求
              # - "http://localhost:8081"
            allowedMethods: # 允许的跨域ajax的请求方式
              - "GET"
              - "POST"
              - "DELETE"
              - "PUT"
              - "OPTIONS"
            allowedHeaders: "*" # 允许在请求中携带的头信息
            allowCredentials: true # 是否允许携带cookie
            maxAge: 360000 # 这次跨域检测的有效期
