server:
  port: 8082
spring:
  cloud:
    gateway:
      enabled: true
      # 开启自动路由
      discovery:
        locator:
          enabled: true
      routes:
        # 字典服务
        - id: base-forge-data-dictionary-v1
          uri: lb://base-forge-data-dictionary
          predicates:
            - Path=/api/v1/dictionary/**
          # filters:
          #   - name: RequestId
        # 认证服务
        - id: base-forge-authentication-v1
          uri: lb://base-forge-authentication
          predicates:
            - Path=/api/v1/auth/c/**
          # filters:
          #   - name: RequestId
        # 授权资源服务
        - id: base-forge-authorization-v1
          uri: lb://base-forge-authorization
          predicates:
            - Path=/api/v1/auth/z/**
      # 全局的跨域处理
      global-cors:
        # 解决options请求被拦截问题
        add-to-simple-url-handler-mapping: true
        corsConfigurations:
          '[/**]':
            allowedOrigins: # 允许哪些网站的跨域请求
              # - "http://192.168.200.131:8081"
              - "http://localhost:5173"
            allowedMethods: # 允许的跨域ajax的请求方式
              - "GET"
              - "POST"
              - "DELETE"
              - "PUT"
              - "OPTIONS"
            allowedHeaders: "*" # 允许在请求中携带的头信息
            allowCredentials: true # 是否允许携带cookie
            maxAge: 360000 # 这次跨域检测的有效期
