spring:
  main:
    allow-bean-definition-overriding: true
    web-application-type: reactive
  application:
    name: base-forge-gateway # 模块名，与配置文件夹名一致
  profiles:
    active: dev
base-forge:
  security:
    authorization:
      request-url: /api/v1/**
      ignored:
        - /api/v1/auth/c/**
