spring:
  rabbitmq:
    host: 172.24.165.5
    port: 5672
    username: gewuyou
    password: E93NN8ziTtAxjD@
    listener:
      simple:
        retry:
          enabled: true
          max-attempts: 3
          initial-interval: 3000
    virtual-host: /base-forge



