spring:
  cloud:
    config:
      server:
        native:
          search-locations: >
            classpath:/conf,
            classpath:/conf/base-forge-discovery,
            classpath:/conf/base-forge-gateway,
            classpath:/conf/base-forge-data-dictionary,
            classpath:/conf/base-forge-authentication,
            classpath:/conf/base-forge-authorization,
