spring:
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/gewuyou/base-forge-config
          username: gewuyou
          #git 私钥
          password:
          search-paths:
            - ""
          default-label: master

