spring:
  cloud:
    config:
      server:
        git:
          #填入你的git仓库地址
          uri: https://gitee.com/gewuyou/base-forge-config
          #填入你的git用户名
          username: gewuyou
          #填入你的git 私钥
          password:
          #填入你的配置路径
          search-paths:
            - ""
            -
          #填入你的默认分支
          default-label: master
