spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: base-forge-authentication
  profiles:
    active: dev
base-forge:
  security:
    authentication:
      base-login-url: /api/auth/c
      logout-url: