spring:
  config:
    import: configserver:http://localhost:8888/
  cloud:
    config:
      profile: dev
      name: >
        ${spring.application.name},
        common-log,common-eureka,
        common-rabbitmq,common-redis,
        common-datasource
base-forge:
  security:
    authentication:
      base-login-url: /auth/login
    authorization:
      request-url: /api/v1/auth/authorize